[tool.poetry]
name = "server-proj"
version = "0.1.0"
description = ""
authors = ["Thijs de Zeeuw <thijs.de.zeeuw8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

[tool.poetry.scripts]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
