import socket

mac_address_server = "D4-5D-64-3D-13-17"

def wake_server(mac_address, port):
    """Wakes a device with specified mac_address over a specified port using a broadcast of the magic packet.
    The magic packet is generated by FF:FF:FF:FF:FF:FF followed by 16 times the mac address.
    Requires Wake on Lan (WOL) to be supported and turned on on the devies that needs to be awakend.

    Args:
        mac_address (str): mac address of device to be awakened
        port (int): unused port on the local network to send out the broadcast signal
    """

    UDP_IP = "192.168.178.255"
    UDP_PORT = port

    mac_address = mac_address.replace(":", "").replace("-", "")
    mac_hex = bytes.fromhex(mac_address)
    
    # magic packet consists of a starting ff string followed by 16 x the mac address
    magic_packet = b"\xff" * 6 + mac_hex * 16

    # broadcast packet over the local network, SOCK_DGRAM so that UDP is used as TCP fails
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:

        # not needed?
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        
        sock.sendto(magic_packet, (UDP_IP, UDP_PORT))



if __name__ == "__main__":
    wake_server("d4:5d:64:3d:13:17", port=6942)