import datetime
import socket

time = datetime.datetime.now().time()


def wake_server(mac_address, port):
    """Wakes a device with specified mac_address over a specified port using a broadcast of the magic packet.
    The magic packet is generated by FF:FF:FF:FF:FF:FF followed by 16 times the mac address.
    Requires Wake on Lan (WOL) to be supported and turned on on the devies that needs to be awakend.

    Args:
        mac_address (str): mac address of device to be awakened
        port (int): unused port on the local network to send out the broadcast signal
    """

    mac_address = bytes.fromhex(mac_address.replace(":", "").replace("-", ""))

    # magic packet consists of a starting ff string followed by 16 x the mac address
    magic_packet = b'\xFF'*6 + mac_address * 16

    # broadcast packet over the local network
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
        sock.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)

        sock.sendto(magic_packet, ("<broadcast>", port))



if __name__ == "__main__":
    wake_server("3C-58-C2-4C-C8-EF", port=9)